### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ksmadhuri** [INFO526-DataViz/project-01-DataInk-Drinkers#1]
The following is the peer review of the project proposal by [Aes-thetics-Squad]. The team members that participated in this review are 

- [Sai Madhuri Kandula] - @[ksmadhuri]
- [Priyarsha Vallabhaneni] - @[Priyarsha31]
- [Ansh Kumar Dev] - @[Anshkumardev]
- [jothish Kumar Polaki] - @[Jothish21]

- Describe the goal of the project.
To uncover potential trends and correlations of unexplained UFO encounters.

- Describe the data used or collected.
They are using the 2 files namely ufo_sighting.csv and places.csv. This dataset is collected from the tidytuesday platform.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Question 1 approach: After loading the data and ensuring correct data types, data pertaining to day, month and year are aggregated to cite the trends and then finally use bubble maps to visualize it. 
Also, added time series plots for temporal distribution.
Question 2 approach: To visualize the total number of sightings for each year, use lineplots or density plots to gain insights on diurnal patterns.

- Is there anything that is unclear from the proposal?
From the question 1 , it was unclear about how do you visualize the UFO sightings trends based on dates in bubble maps. Maybe you should rephrase the question as What are the UFO sighting years and locations globally?

- Provide constructive feedback on how the team might be able to improve their project.
For the question 2, maybe you can use more variables since the given variable "reported_date_time" is already used for analysis in question 1.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested about the bubble maps to see how it works with latitude and longitude data and if there are any particular states with most occurrences.

- Provide constructive feedback on any issues with file and/or code organization.
The code is properly organized and they aren't any issues with the file.

- (Optional) Any further comments or feedback?

**Comment by TejashwiniKasa** [comment]
Hi Team,
We have made the changes accordingly.
Thankyou very much for your feedback.
 -DataInk Drinkers
