### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by meganhokama** [INFO526-DataViz/project-01-DataInk-Drinkers#2]
The following is the peer review of the project proposal by [The Plotting Pandas]. The team members that participated in this review are 

Maria Nikitha Suresh - [@marianikitha01](https://github.com/marianikitha01)

Megan Hokama - [@meganhokama](https://github.com/meganhokama)

Shakir Ahmed - [@Shakir0585](https://github.com/Shakir0585)

Eshaan Mathakari.- [@eshaanmathakari](https://github.com/eshaanmathakari)

Bharath Velamala - [@bharath03-a](https://github.com/bharath03-a)
- ...

- Describe the goal of the project.
The project aims to examine the UFO sightings datasets with the goal of studying the correlations and patterns of global UFO sightings. Based on the research questions posed, the goal is to identify trends between UFO sightings locations and dates, as well as, investigate the development of UFO sightings over time. Ultimately, the team wants to derive relationship patterns of UFO sightings through diverse plot analyses (e.g., time series plots) with the potential to explore predictive models.

- Describe the data used or collected.
The data being used is from two files from the provided tidytuesday dataset which are ufo_sighting.csv and places.csv, each of which contains 96429 observations of 12 variables and 14417 instances of variables, respectively. The data has some insightful variables such as reported_date_time, city, state, country_code, day_part , latitude and longitude. Looking at the proposal we can find that most of the data contains the parameters related to when and where the UFO sightings have occurred.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
A. For Question 1: Data is going to be read directly from Github URL using the read.csv() command. Cleaning of data is going to be performed to ensure that the dates and locations are of the correct data type (e.g. Date should be in standard date format). From here, certain elements are going taken into consideration for visualization, like reported_date_time, city, state, country_code. A geographic plot is going to be used for visualizations for visualizing on a global scale, with marking bubbles in bubble map using the Latitude and Longitude details from the 'longitude' and 'latitude' information in city, state, and country_code columns.
Additionally, a time series/bar/line chart is going to used to visualize the correlations between the sighting characteristics, dates and locations to determine trends/patterns.
B. For Question 2:  Data manipulation is going to be performed to create a new column using the mutate() function, to create a new column for extracting the year only from all the dates. Further, grouping is going to be performed by year, and a total count per year i going to be extracted. One consideration for visualization is going to be a geom_treemap plot to visualize timings of sightings for particular years.
To discern the trends in UFO sightings, a line/bar/density/histogram is going to be used to plot and check if there are any trends in sightings, either during a season of any particular time of day.

- Is there anything that is unclear from the proposal?
Since the first question is a little confusing and challenging to understand, the solution is also somewhat difficult to grasp.  Apart from that, everything else is quite clear.

- Provide constructive feedback on how the team might be able to improve their project.
A. It would have been a bit clear if it was mentioned from which data you are planning to use the mentioned variables for Q1 and Q2, since you have two data ufo_sighting.csv and places.csv.
B. Project title is missing in the navbar, it will be cool to add it :)
C. It would have been nice to have your information written in the about page since it will give us some insight on who has done the project.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in the potential patterns and correlations that can be uncovered within the UFO sightings dataset. This dataset offers a unique opportunity to explore and analyze unexplained aerial phenomena, shedding light on the mysterious world of UFO sightings. We would like to see this aspect highlighted in the presentation, particularly any insights or findings that may emerge from the data visualizations. Understanding patterns and correlations in UFO sightings could provide valuable scientific and anecdotal perspectives on these enigmatic events, which aligns with the enduring fascination that researchers and enthusiasts have for this subject.

- Provide constructive feedback on any issues with file and/or code organization.
While describing the properties of the data, you seemed to miss mentioning the number of variables/columns present in the places.csv data. Might be informative to add in your next iteration.

- (Optional) Any further comments or feedback?
Nothing major, just a minor feedback. We understand that why you have hidden the part where you read the data, but it would have been better if it was included in the webpage by excluding the output generated by that code chunk.

***All the best for your project on UFO sightings, we are looking forward to seeing the final analyses :) - Team The Plotting Pandas

**Comment by Swati09Das** [comment]
Hi Team,

We have made the changes accordingly.
Thank you very much for your feedback.

- DataInk Drinkers
