### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-DataInk-Drinkers#3]
Dear DataInk-Drinkers: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3 |
| Proposal | 5         |        3|
| Workflow | 1         |       1 |
| Teamwork | 1         |       1 |
| Total    | 10        |       8 |

Good work overall, I have some minor issues for you to fix to be eligible for full credit:
1. "line charts or bar charts can be used depending on the granularity of the time period." Be more definitive here - e.g., choose line plots since bar plots won't really be as effective as you might think. 
2. You did not describe the variables or show the columns, so it is unclear what the variables actually are. 
3. Check for typos, there one minor one that I can find: "question 1.A new column has". 
4. Describe the plots a little more, specifically why you chose it and what it will tell you - e.g., `geom_treemap`.

**Comment by Swati09Das** [comment]
Hello Dr. Greg,

Thank you for your feedback. We have gone through our proposal once and made the changes.

Kindly review it once again.

Regards,
~Team DataInk Drinkers

**Comment by Gchism94** [comment]
Looks good now, great work! Your final score for the proposal is 9/10.

**Comment by partha-pkp** [comment]
Hi Dr. Greg,

Thank you very much for the regrade.

Thanks and Regards,
~Team DataInk Drinkers
