### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by datalyticsintel** [INFO526-DataViz/project-01-DataInk-Drinkers#4]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

- Akrant Varshney, - @AkrantVarshney
- Hariharan Ramesh - @hari1016
- Thanoosha Naidu Karri - @thanooshakarri
- Antonio Escalante Jr. - @datalyticsintel

- Content: Is the research question well designed and is the data being used relevant to the research question?
Both were great and well-designed for their dataset.
- What are the number of UFO encounters globally?
- How did the trend of UFO sightings vary over the years?

As Greg pointed out, there was almost a 3rd question with the 2nd question, which made it a little confusing and unfocused, but all questions were answered and made sense when further explained. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The team used a variety of visualizations, including bubble plots and treemaps. However, there were issues with the visualizations. There was some use of unnecessary image backgrounds and inconsistencies in the document theme. The use of the leaflet package instead of ggplot2 was also noted, but they could plot out what they wanted with the data. Improving the labeling in the bubble plot may help the audience understand better but overall, it was good. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The use of a treemap to show occurrences was highlighted as a creative idea. However, there were several criticisms regarding the choice of visualizations and their design as not all images used were useful. We did like the twilight infographic. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
 Issues with the consistency of the document theme, different backgrounds for trends and bar plots, and inconsistencies in titles and axes. The use of unnecessary colors in the facetwrap and bar plots. It suggests that there might have been issues with the organization and was kind of hard to read some slides since some people asked additional clarification questions, but the group was able to answer them. They were well prepared.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
They worked together well. Everyone got a chance to contribute to the project and said something about the process in which they had a part.

Overall the did a wonderful job and should receive full points.

**Comment by Gchism94** [comment]
Based on the peer-review, I am awarding 4.5/5, despite the recommendation for full points. There were noted issues with the presentation that can't be ignored.

**Comment by partha-pkp** [comment]
Hi Dr Greg,
Thank you for the feedback!

- DataInk Drinkers
