### ISSUE TITLE
Write-up feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-DataInk-Drinkers#6]
Dear DataInk Drinkers: Below is the score breakdown for your write-up. 

## Write-up

|          | Available | Earned |
|----------|-----------|--------|
| Introduction     | 2         |    2    |
| Justification of approach | 6 (3/Question)         |    5    |
| Code | 6 (3/Question)         |    6    |
| Visualization | 8 (4/Question)         |    8    |
| Discussion | 8 (4/Question) | 8 |
| Total    | 30        |   29     |

Feedback: 
I am not convinced that the number of sightings over times of the belongs in Q2 and there isn't sufficient justification for this. A minor issue too is that the theme for the facets should be `theme_minimal` to provide more contrast with the lines (especially the gray one).

**Comment by partha-pkp** [comment]
Hi Dr Greg,
Thank you for the feedback!

~ DataInk Drinkers
