### ISSUE TITLE
Reproducibility, style, and organization feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-DataInk-Drinkers#7]
Dear DataInk Drinkers: Below is the score breakdown for your project Reproducibility, style, and organization. 

## Reproducibility, style, and organization 

|          | Available | Earned |
|----------|-----------|--------|
| All required files are provided.<br>Quarto files render without issues and reproduce the necessary outputs.     | 3         |    3    |
| Data is in the data folder, with a codebook in the README,<br>and is loaded from this folder in presentation and writeup. | 3         |        2.5 |
| Documents are well structured and easy to follow.<br>No extraneous materials.  | 2         |   2     |
| All issues are closed,<br>mostly with specific commits addressing them. | 2 | 2 |
| Total    | 10        |    9.5    |

Feedback:
Minor issue - your `data` folder should have a complete README file

**Comment by partha-pkp** [comment]
Hi Dr Greg,
Thank you for the feedback!

~ DataInk Drinkers
